/**
 * APPROVED PUBLIC DATA CONTRACT
 *
 * All programmatic content generated by the acquisition layer must be sourced
 * strictly from approved, verified public records or read-only public interfaces.
 * Never accesses private user tables, core auth state, or transactions.
 */

export interface PublicBusinessRecord {
  slug: string;
  name: string;
  category: string;
  city: string;
  verificationStatus: 'verified_official' | 'trusted_merchant';
  features: string[];
  description: string;
}

export interface PublicJobScreeningRecord {
  slug: string;
  role: string;
  industry: string;
  city: string;
  screeningQuestions: string[];
  responsibilities: string[];
  qualifications: string[];
  typicalSalaryRange: string;
}

export interface PublicLanguagePairRecord {
  slug: string;
  sourceLanguage: string;
  targetLanguage: string;
  nativeSource: string;
  nativeTarget: string;
  useCase: string;
  commonPhrases: Array<{ original: string; translated: string; context: string }>;
  linguisticNotes: string;
}

export interface PublicComparisonRecord {
  slug: string;
  competitor: string;
  comparisonTitle: string;
  summary: string;
  dimensions: Array<{
    feature: string;
    chatrApproach: string;
    competitorApproach: string;
  }>;
}

export interface PublicCityRecord {
  slug: string;
  cityName: string;
  state: string;
  primaryLanguages: string[];
  businessHubs: string[];
  localDialectNotes: string;
}

// ── Approved Public Records ──────────────────────────────────────────

export const APPROVED_BUSINESSES: PublicBusinessRecord[] = [
  {
    slug: 'talentxcel-official',
    name: 'Talentxcel Services',
    category: 'Recruitment & HR Tech',
    city: 'Bengaluru',
    verificationStatus: 'verified_official',
    features: ['Automated Candidate Screening', 'Direct Verified Calls', 'Encrypted Document Exchange'],
    description: 'Official verified enterprise account providing automated hiring workflows and candidate interviews on Chatr.'
  },
  {
    slug: 'rapidcare-clinics',
    name: 'RapidCare Health Network',
    category: 'Healthcare & Diagnostics',
    city: 'Mumbai',
    verificationStatus: 'verified_official',
    features: ['Appointment Scheduling', 'Emergency Audio Calls', 'Digital Prescription Dispatch'],
    description: 'Verified healthcare provider facilitating appointment scheduling and doctor tele-consultation channels.'
  },
  {
    slug: 'quicklogix-logistics',
    name: 'QuickLogix Express',
    category: 'Supply Chain & Delivery',
    city: 'Delhi',
    verificationStatus: 'trusted_merchant',
    features: ['Real-time Dispatch Updates', 'Driver Voice Hand-off', 'Proof of Delivery'],
    description: 'B2B logistics provider offering transparent communication for shipment routing and delivery drivers.'
  }
];

export const APPROVED_JOB_SCREENINGS: PublicJobScreeningRecord[] = [
  {
    slug: 'delivery-executive-bengaluru',
    role: 'Delivery Executive',
    industry: 'Logistics & Quick Commerce',
    city: 'Bengaluru',
    screeningQuestions: [
      'Do you own a valid two-wheeler driving license and smartphone?',
      'Which zones in Bengaluru are you most familiar with (e.g. Indiranagar, Koramangala, Whitefield)?',
      'Are you available for flexible weekend shifts?'
    ],
    responsibilities: [
      'Deliver packages and food orders within assigned geographic clusters safely.',
      'Communicate with customers via Chatr voice or text when locating addresses.',
      'Complete pre-delivery and post-delivery condition checklists.'
    ],
    qualifications: ['Valid Driving License', 'Two-wheeler Vehicle', 'Smartphone with GPS'],
    typicalSalaryRange: '₹18,000 – ₹28,000 per month + incentives'
  },
  {
    slug: 'customer-support-associate-mumbai',
    role: 'Customer Support Associate',
    industry: 'E-commerce & SaaS',
    city: 'Mumbai',
    screeningQuestions: [
      'How many years of experience do you have handling high-volume voice/chat tickets?',
      'Are you fluent in Hindi, Marathi, and conversational English?',
      'Describe a situation where you resolved a frustrated customer dispute.'
    ],
    responsibilities: [
      'Answer customer inquiries through omni-channel messaging and voice calls.',
      'Troubleshoot account, order delivery, and billing questions.',
      'Log structured ticket resolutions with accurate internal notes.'
    ],
    qualifications: ['Higher Secondary (10+2) or Graduate', 'Fluent in Hindi & English', 'Basic computer literacy'],
    typicalSalaryRange: '₹22,000 – ₹35,000 per month'
  },
  {
    slug: 'sales-development-representative-delhi',
    role: 'Sales Development Representative',
    industry: 'B2B Technology',
    city: 'Delhi NCR',
    screeningQuestions: [
      'What is your track record in booking outbound qualified meetings?',
      'Are you comfortable conducting screening discovery calls?',
      'What CRM tools (e.g. HubSpot, Salesforce) have you worked with?'
    ],
    responsibilities: [
      'Reach out to inbound and outbound business prospects via verified chat and calls.',
      'Qualify business requirements and schedule discovery demonstrations.',
      'Maintain pipeline data cleanliness.'
    ],
    qualifications: ['Bachelor degree', '1+ years outbound SDR experience', 'Strong written & verbal communication'],
    typicalSalaryRange: '₹30,000 – ₹45,000 per month + commissions'
  }
];

export const APPROVED_LANGUAGE_PAIRS: PublicLanguagePairRecord[] = [
  {
    slug: 'hindi-to-tamil',
    sourceLanguage: 'Hindi',
    targetLanguage: 'Tamil',
    nativeSource: 'हिन्दी',
    nativeTarget: 'தமிழ்',
    useCase: 'Interstate interstate trade and nationwide customer calls',
    commonPhrases: [
      { original: 'नमस्ते, क्या आप मेरी बात सुन पा रहे हैं?', translated: 'வணக்கம், நான் பேசுவது கேட்கிறதா?', context: 'Call opening check' },
      { original: 'सामान कब तक डिलीवर होगा?', translated: 'பொருட்கள் எப்போது வந்து சேரும்?', context: 'Delivery timeline' },
      { original: 'धन्यवाद, मैं आपको चैट पर विवरण भेज रहा हूँ।', translated: 'நன்றி, விவரங்களை சாட்டில் அனுப்புகிறேன்.', context: 'Sending details' }
    ],
    linguisticNotes: 'Grammar structure differences: Hindi uses Subject-Object-Verb (SOV) with gender agreement, while Tamil is agglutinative with gender-neutral verb forms in second person.'
  },
  {
    slug: 'marathi-to-hindi',
    sourceLanguage: 'Marathi',
    targetLanguage: 'Hindi',
    nativeSource: 'मराठी',
    nativeTarget: 'हिन्दी',
    useCase: 'Maharashtra intra-regional business and service communication',
    commonPhrases: [
      { original: 'नमस्कार, तुमचे काम कधी पूर्ण होईल?', translated: 'नमस्ते, आपका काम कब तक पूरा होगा?', context: 'Project milestone query' },
      { original: 'मी तुम्हाला लगेच लोकेशन पाठवतो.', translated: 'मैं आपको तुरंत लोकेशन भेजता हूँ।', context: 'Location dispatch' },
      { original: 'आम्ही संध्याकाळी भेटू शकतो का?', translated: 'क्या हम शाम को मिल सकते हैं?', context: 'Scheduling a call' }
    ],
    linguisticNotes: 'High lexical overlap through shared Devanagari script and Indo-Aryan ancestry, with key differences in postpositions and causative verbs.'
  },
  {
    slug: 'punjabi-to-english',
    sourceLanguage: 'Punjabi',
    targetLanguage: 'English',
    nativeSource: 'ਪੰਜਾਬੀ',
    nativeTarget: 'English',
    useCase: 'Diaspora family calls and international business consultations',
    commonPhrases: [
      { original: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਕੀ ਹਾਲ ਚਾਲ ਹੈ?', translated: 'Hello, how are you doing?', context: 'Friendly greeting' },
      { original: 'ਮੈਂ ਕੱਲ੍ਹ ਸਵੇਰੇ ਤੁਹਾਨੂੰ ਕਾਲ ਕਰਾਂਗਾ।', translated: 'I will call you tomorrow morning.', context: 'Call scheduling' },
      { original: 'ਸਾਰੀਆਂ ਜਾਣਕਾਰੀਆਂ ਈਮੇਲ ਕਰ ਦਿੱਤੀਆਂ ਹਨ।', translated: 'All information has been sent over.', context: 'Status update' }
    ],
    linguisticNotes: 'Tonal variations in Punjabi (high, low, level pitch) mapped directly to clear English intonation.'
  }
];

export const APPROVED_COMPARISONS: PublicComparisonRecord[] = [
  {
    slug: 'chatr-vs-truecaller-privacy',
    competitor: 'Truecaller',
    comparisonTitle: 'Chatr vs Truecaller: Privacy-First Caller Defense',
    summary: 'A direct comparison of caller identification, contact book upload requirements, advertising models, and data privacy safeguards.',
    dimensions: [
      {
        feature: 'Contact Book Upload',
        chatrApproach: 'Zero phonebook crowd-sourcing. Your contacts stay private on your device.',
        competitorApproach: 'Crowdsources address books into a searchable public global directory.'
      },
      {
        feature: 'Ad-Supported Model',
        chatrApproach: '100% Ad-Free experience. Zero intrusive full-screen banners or call overlays.',
        competitorApproach: 'Ad-supported free tier with frequent banner and interstitial promotions.'
      },
      {
        feature: 'Live Call Translation',
        chatrApproach: 'Built-in real-time speech translation and AI call summaries.',
        competitorApproach: 'Does not offer real-time multilingual voice translation during calls.'
      },
      {
        feature: 'Account Architecture',
        chatrApproach: 'One phone number, zero password friction, encrypted transit.',
        competitorApproach: 'Requires email, third-party social logins, and extensive profile permissions.'
      }
    ]
  },
  {
    slug: 'chatr-vs-whatsapp-business-screening',
    competitor: 'WhatsApp Business',
    comparisonTitle: 'Chatr vs WhatsApp Business for Candidate Screening',
    summary: 'How Chatr automated screening flows compare with standard WhatsApp Business quick replies and catalog setups.',
    dimensions: [
      {
        feature: 'Automated Candidate Screening',
        chatrApproach: 'Built-in SI screening questions that auto-summarize applicant readiness.',
        competitorApproach: 'Requires third-party BSP APIs, third-party bots, and complex webhook setups.'
      },
      {
        feature: 'Per-Conversation Charges',
        chatrApproach: 'Free direct messaging without Meta utility/marketing per-message conversation fees.',
        competitorApproach: 'Charges businesses per 24-hour conversation window based on country tier.'
      },
      {
        feature: 'Live Translation in Calls',
        chatrApproach: 'Live translated audio & captions on voice calls between languages.',
        competitorApproach: 'Standard VoIP without speech-to-speech translation.'
      }
    ]
  }
];

export const APPROVED_CITIES: PublicCityRecord[] = [
  {
    slug: 'mumbai',
    cityName: 'Mumbai',
    state: 'Maharashtra',
    primaryLanguages: ['Marathi', 'Hindi', 'English'],
    businessHubs: ['BKC', 'Lower Parel', 'Nariman Point', 'Andheri East'],
    localDialectNotes: 'High prevalence of Bambaiya Hindi mixed with Marathi and Gujarati loanwords.'
  },
  {
    slug: 'delhi',
    cityName: 'Delhi',
    state: 'Delhi NCR',
    primaryLanguages: ['Hindi', 'Punjabi', 'English', 'Urdu'],
    businessHubs: ['Connaught Place', 'Cyber City', 'Noida Sector 62', 'Aerocity'],
    localDialectNotes: 'Mix of standard Khari Boli Hindi with Punjabi business terminology.'
  },
  {
    slug: 'bengaluru',
    cityName: 'Bengaluru',
    state: 'Karnataka',
    primaryLanguages: ['Kannada', 'English', 'Hindi', 'Tamil', 'Telugu'],
    businessHubs: ['Whitefield', 'Electronic City', 'Koramangala', 'Indiranagar'],
    localDialectNotes: 'Multilingual tech workforce frequently code-switching between Kannada, English, and Hindi.'
  }
];
